apiVersion: v1
kind: Pod
metadata:
  name: test-pod-{YOUR_NAME}
spec:
  containers:
    - name: mypod
      image: ubuntu
      command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
      resources:
        limits:
            memory: 100Mi
            cpu: 100m
        requests:
            memory: 100Mi
            cpu: 100m
      volumeMounts: #optional, for mounting PVC
          - mountPath: /mnt/pvc
            name: storage-volume
  volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: pvc-hongao