apiVersion: v1
kind: Pod
metadata:
  name: test-pod-hongao
spec:
  containers:
  - name: mypod
    image: hongao/nautilus:mnist
    command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
    resources:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 100Mi
        cpu: 100m
