apiVersion: v1
kind: Pod
metadata:
  name: test-pod-{YOUR_NAME}
spec:
  affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - matchExpressions:
         - key: nvidia.com/gpu.product
           operator: In
           values:
           - NVIDIA-GeForce-RTX-3090
  containers:
  - name: mypod
    image: hongao/nautilus:mnist
    command: ["/bin/bash", "-c"]
    args:
      - |
        git clone https://github.com/lemn-lab/nautilus-tutorial.git /app/code && \
        echo "the pod is ready" && \
        cd /app/code && \
        sleep infinity
    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
    resources:
      limits:
        memory: 8Gi
        cpu: "4"
        nvidia.com/gpu: "1"
      requests:
        memory: 8Gi
        cpu: "4"
        nvidia.com/gpu: "1"
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 1Gi
